### ISSUE TITLE
Question with intelissense

### ISSUE THREAD

**Issue by tomasvn** [wkillerud/vscode-scss#35] opened 2023-01-19 13:34 UTC
Hello, I'd like to ask about intellisense using `@use` and package from `node_modules`. Do I have set some settings in extension's config? Tried to remove `node_modules` from somesass scanner @wkillerud

**Comment by wkillerud** [comment] 2023-02-01 15:23
Closing as duplicate of #36

**Closed by wkillerud** 2023-02-01 15:23 UTC
